// -----------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY scripts/generate-archives.mjs
// DO NOT EDIT MANUALLY.
//
// DATA SECURITY:
// - Descriptions are AES-256-GCM Encrypted.
// - Keys derived via PBKDF2 (100k iterations).
// - Plaintext passwords are STRIPPED from this file.
// -----------------------------------------------------------------------------

import { ArchiveItem } from '../types';

export const archiveData: ArchiveItem[] = [
  {
    id: 'op001',
    title: 'INV/LV/000001',
    status: 'Completed',
    tags: ["Blockchain","Cryptography","dApp"],
    description: {
      en: {
        cipher: 'PLACEHOLDER_CIPHER',
        iv: 'PLACEHOLDER_IV',
        salt: 'PLACEHOLDER_SALT'
      },
      id: {
        cipher: 'PLACEHOLDER_CIPHER',
        iv: 'PLACEHOLDER_IV',
        salt: 'PLACEHOLDER_SALT'
      }
    }
  },
  {
    id: 'op002',
    title: 'INV/LV/000002',
    status: 'Completed',
    tags: ["Pentesting","Red Team","Security"],
    description: {
      en: {
        cipher: 'PLACEHOLDER_CIPHER',
        iv: 'PLACEHOLDER_IV',
        salt: 'PLACEHOLDER_SALT'
      },
      id: {
        cipher: 'PLACEHOLDER_CIPHER',
        iv: 'PLACEHOLDER_IV',
        salt: 'PLACEHOLDER_SALT'
      }
    }
  }
];