// -----------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY scripts/generate-dispatches.mjs
// DO NOT EDIT MANUALLY. ADD NEW DISPATCH FILES TO data/dispatches/
// -----------------------------------------------------------------------------

import { DispatchSummary, LocalizedContent } from '../types';
import { d001_meta } from './dispatches/d001';
import { d002_meta } from './dispatches/d002';
import { d003_meta } from './dispatches/d003';

const list: DispatchSummary[] = [d001_meta, d002_meta, d003_meta];

/**
 * Pre-sorted list to ensure stability across SSR/Hydration
 */
export const dispatchesList: DispatchSummary[] = list
  .filter(item => item && item.id && item.slug)
  .sort((a, b) => {
    const timeA = new Date(a.timestamp).getTime();
    const timeB = new Date(b.timestamp).getTime();
    return timeB - timeA;
  });

// Dynamic loader for heavy content
export const loadDispatchContent = async (id: string): Promise<LocalizedContent | null> => {
  try {
    switch (id) {
      case 'd001':
        return (await import('./dispatches/d001')).d001_content;
      case 'd002':
        return (await import('./dispatches/d002')).d002_content;
      case 'd003':
        return (await import('./dispatches/d003')).d003_content;
      default:
        return null;
    }
  } catch (e) {
    console.error(`Failed to load content for ${id}`, e);
    return null;
  }
};